package yycg.business.pojo.po;

import java.util.Date;

public class Ypxx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.BM
     *
     * @mbggenerated
     */
    private String bm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.SCQYMC
     *
     * @mbggenerated
     */
    private String scqymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.SPMC
     *
     * @mbggenerated
     */
    private String spmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ZBJG
     *
     * @mbggenerated
     */
    private Float zbjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ZPDZ
     *
     * @mbggenerated
     */
    private String zpdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.PZWH
     *
     * @mbggenerated
     */
    private String pzwh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.PZWHYXQ
     *
     * @mbggenerated
     */
    private Date pzwhyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.JKY
     *
     * @mbggenerated
     */
    private String jky;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.BZCZ
     *
     * @mbggenerated
     */
    private String bzcz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.BZDW
     *
     * @mbggenerated
     */
    private String bzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.LSJG
     *
     * @mbggenerated
     */
    private Double lsjg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.LSJGCC
     *
     * @mbggenerated
     */
    private String lsjgcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ZLCC
     *
     * @mbggenerated
     */
    private String zlcc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ZLCCSM
     *
     * @mbggenerated
     */
    private String zlccsm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.YPJYBG
     *
     * @mbggenerated
     */
    private String ypjybg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.YPJYBGBM
     *
     * @mbggenerated
     */
    private String ypjybgbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.YPJYBGYXQ
     *
     * @mbggenerated
     */
    private Date ypjybgyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.JYZT
     *
     * @mbggenerated
     */
    private String jyzt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.DW
     *
     * @mbggenerated
     */
    private String dw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.JX
     *
     * @mbggenerated
     */
    private String jx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.GG
     *
     * @mbggenerated
     */
    private String gg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.ZHXS
     *
     * @mbggenerated
     */
    private String zhxs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.PINYIN
     *
     * @mbggenerated
     */
    private String pinyin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.LB
     *
     * @mbggenerated
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column YPXX.CPSM
     *
     * @mbggenerated
     */
    private String cpsm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ID
     *
     * @return the value of YPXX.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ID
     *
     * @param id the value for YPXX.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.BM
     *
     * @return the value of YPXX.BM
     *
     * @mbggenerated
     */
    public String getBm() {
        return bm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.BM
     *
     * @param bm the value for YPXX.BM
     *
     * @mbggenerated
     */
    public void setBm(String bm) {
        this.bm = bm == null ? null : bm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.SCQYMC
     *
     * @return the value of YPXX.SCQYMC
     *
     * @mbggenerated
     */
    public String getScqymc() {
        return scqymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.SCQYMC
     *
     * @param scqymc the value for YPXX.SCQYMC
     *
     * @mbggenerated
     */
    public void setScqymc(String scqymc) {
        this.scqymc = scqymc == null ? null : scqymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.SPMC
     *
     * @return the value of YPXX.SPMC
     *
     * @mbggenerated
     */
    public String getSpmc() {
        return spmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.SPMC
     *
     * @param spmc the value for YPXX.SPMC
     *
     * @mbggenerated
     */
    public void setSpmc(String spmc) {
        this.spmc = spmc == null ? null : spmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ZBJG
     *
     * @return the value of YPXX.ZBJG
     *
     * @mbggenerated
     */
    public Float getZbjg() {
        return zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ZBJG
     *
     * @param zbjg the value for YPXX.ZBJG
     *
     * @mbggenerated
     */
    public void setZbjg(Float zbjg) {
        this.zbjg = zbjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ZPDZ
     *
     * @return the value of YPXX.ZPDZ
     *
     * @mbggenerated
     */
    public String getZpdz() {
        return zpdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ZPDZ
     *
     * @param zpdz the value for YPXX.ZPDZ
     *
     * @mbggenerated
     */
    public void setZpdz(String zpdz) {
        this.zpdz = zpdz == null ? null : zpdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.PZWH
     *
     * @return the value of YPXX.PZWH
     *
     * @mbggenerated
     */
    public String getPzwh() {
        return pzwh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.PZWH
     *
     * @param pzwh the value for YPXX.PZWH
     *
     * @mbggenerated
     */
    public void setPzwh(String pzwh) {
        this.pzwh = pzwh == null ? null : pzwh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.PZWHYXQ
     *
     * @return the value of YPXX.PZWHYXQ
     *
     * @mbggenerated
     */
    public Date getPzwhyxq() {
        return pzwhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.PZWHYXQ
     *
     * @param pzwhyxq the value for YPXX.PZWHYXQ
     *
     * @mbggenerated
     */
    public void setPzwhyxq(Date pzwhyxq) {
        this.pzwhyxq = pzwhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.JKY
     *
     * @return the value of YPXX.JKY
     *
     * @mbggenerated
     */
    public String getJky() {
        return jky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.JKY
     *
     * @param jky the value for YPXX.JKY
     *
     * @mbggenerated
     */
    public void setJky(String jky) {
        this.jky = jky == null ? null : jky.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.BZCZ
     *
     * @return the value of YPXX.BZCZ
     *
     * @mbggenerated
     */
    public String getBzcz() {
        return bzcz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.BZCZ
     *
     * @param bzcz the value for YPXX.BZCZ
     *
     * @mbggenerated
     */
    public void setBzcz(String bzcz) {
        this.bzcz = bzcz == null ? null : bzcz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.BZDW
     *
     * @return the value of YPXX.BZDW
     *
     * @mbggenerated
     */
    public String getBzdw() {
        return bzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.BZDW
     *
     * @param bzdw the value for YPXX.BZDW
     *
     * @mbggenerated
     */
    public void setBzdw(String bzdw) {
        this.bzdw = bzdw == null ? null : bzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.LSJG
     *
     * @return the value of YPXX.LSJG
     *
     * @mbggenerated
     */
    public Double getLsjg() {
        return lsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.LSJG
     *
     * @param lsjg the value for YPXX.LSJG
     *
     * @mbggenerated
     */
    public void setLsjg(Double lsjg) {
        this.lsjg = lsjg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.LSJGCC
     *
     * @return the value of YPXX.LSJGCC
     *
     * @mbggenerated
     */
    public String getLsjgcc() {
        return lsjgcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.LSJGCC
     *
     * @param lsjgcc the value for YPXX.LSJGCC
     *
     * @mbggenerated
     */
    public void setLsjgcc(String lsjgcc) {
        this.lsjgcc = lsjgcc == null ? null : lsjgcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ZLCC
     *
     * @return the value of YPXX.ZLCC
     *
     * @mbggenerated
     */
    public String getZlcc() {
        return zlcc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ZLCC
     *
     * @param zlcc the value for YPXX.ZLCC
     *
     * @mbggenerated
     */
    public void setZlcc(String zlcc) {
        this.zlcc = zlcc == null ? null : zlcc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ZLCCSM
     *
     * @return the value of YPXX.ZLCCSM
     *
     * @mbggenerated
     */
    public String getZlccsm() {
        return zlccsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ZLCCSM
     *
     * @param zlccsm the value for YPXX.ZLCCSM
     *
     * @mbggenerated
     */
    public void setZlccsm(String zlccsm) {
        this.zlccsm = zlccsm == null ? null : zlccsm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.YPJYBG
     *
     * @return the value of YPXX.YPJYBG
     *
     * @mbggenerated
     */
    public String getYpjybg() {
        return ypjybg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.YPJYBG
     *
     * @param ypjybg the value for YPXX.YPJYBG
     *
     * @mbggenerated
     */
    public void setYpjybg(String ypjybg) {
        this.ypjybg = ypjybg == null ? null : ypjybg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.YPJYBGBM
     *
     * @return the value of YPXX.YPJYBGBM
     *
     * @mbggenerated
     */
    public String getYpjybgbm() {
        return ypjybgbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.YPJYBGBM
     *
     * @param ypjybgbm the value for YPXX.YPJYBGBM
     *
     * @mbggenerated
     */
    public void setYpjybgbm(String ypjybgbm) {
        this.ypjybgbm = ypjybgbm == null ? null : ypjybgbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.YPJYBGYXQ
     *
     * @return the value of YPXX.YPJYBGYXQ
     *
     * @mbggenerated
     */
    public Date getYpjybgyxq() {
        return ypjybgyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.YPJYBGYXQ
     *
     * @param ypjybgyxq the value for YPXX.YPJYBGYXQ
     *
     * @mbggenerated
     */
    public void setYpjybgyxq(Date ypjybgyxq) {
        this.ypjybgyxq = ypjybgyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.JYZT
     *
     * @return the value of YPXX.JYZT
     *
     * @mbggenerated
     */
    public String getJyzt() {
        return jyzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.JYZT
     *
     * @param jyzt the value for YPXX.JYZT
     *
     * @mbggenerated
     */
    public void setJyzt(String jyzt) {
        this.jyzt = jyzt == null ? null : jyzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.VCHAR1
     *
     * @return the value of YPXX.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.VCHAR1
     *
     * @param vchar1 the value for YPXX.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.VCHAR2
     *
     * @return the value of YPXX.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.VCHAR2
     *
     * @param vchar2 the value for YPXX.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.VCHAR3
     *
     * @return the value of YPXX.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.VCHAR3
     *
     * @param vchar3 the value for YPXX.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.DW
     *
     * @return the value of YPXX.DW
     *
     * @mbggenerated
     */
    public String getDw() {
        return dw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.DW
     *
     * @param dw the value for YPXX.DW
     *
     * @mbggenerated
     */
    public void setDw(String dw) {
        this.dw = dw == null ? null : dw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.MC
     *
     * @return the value of YPXX.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.MC
     *
     * @param mc the value for YPXX.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.JX
     *
     * @return the value of YPXX.JX
     *
     * @mbggenerated
     */
    public String getJx() {
        return jx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.JX
     *
     * @param jx the value for YPXX.JX
     *
     * @mbggenerated
     */
    public void setJx(String jx) {
        this.jx = jx == null ? null : jx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.GG
     *
     * @return the value of YPXX.GG
     *
     * @mbggenerated
     */
    public String getGg() {
        return gg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.GG
     *
     * @param gg the value for YPXX.GG
     *
     * @mbggenerated
     */
    public void setGg(String gg) {
        this.gg = gg == null ? null : gg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.ZHXS
     *
     * @return the value of YPXX.ZHXS
     *
     * @mbggenerated
     */
    public String getZhxs() {
        return zhxs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.ZHXS
     *
     * @param zhxs the value for YPXX.ZHXS
     *
     * @mbggenerated
     */
    public void setZhxs(String zhxs) {
        this.zhxs = zhxs == null ? null : zhxs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.PINYIN
     *
     * @return the value of YPXX.PINYIN
     *
     * @mbggenerated
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.PINYIN
     *
     * @param pinyin the value for YPXX.PINYIN
     *
     * @mbggenerated
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.LB
     *
     * @return the value of YPXX.LB
     *
     * @mbggenerated
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.LB
     *
     * @param lb the value for YPXX.LB
     *
     * @mbggenerated
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column YPXX.CPSM
     *
     * @return the value of YPXX.CPSM
     *
     * @mbggenerated
     */
    public String getCpsm() {
        return cpsm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column YPXX.CPSM
     *
     * @param cpsm the value for YPXX.CPSM
     *
     * @mbggenerated
     */
    public void setCpsm(String cpsm) {
        this.cpsm = cpsm == null ? null : cpsm.trim();
    }
}