package com.yycg.pojo;

public class Basicinfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.VALUE
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.TYPE
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.TAG
     *
     * @mbggenerated
     */
    private String tag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.ISALIVE
     *
     * @mbggenerated
     */
    private String isalive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BASICINFO.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICINFO
     *
     * @mbggenerated
     */
    public Basicinfo(String id, String name, String value, String type, String tag, String isalive, String vchar1, String vchar3, String vchar2) {
        this.id = id;
        this.name = name;
        this.value = value;
        this.type = type;
        this.tag = tag;
        this.isalive = isalive;
        this.vchar1 = vchar1;
        this.vchar3 = vchar3;
        this.vchar2 = vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICINFO
     *
     * @mbggenerated
     */
    public Basicinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.ID
     *
     * @return the value of BASICINFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.ID
     *
     * @param id the value for BASICINFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.NAME
     *
     * @return the value of BASICINFO.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.NAME
     *
     * @param name the value for BASICINFO.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.VALUE
     *
     * @return the value of BASICINFO.VALUE
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.VALUE
     *
     * @param value the value for BASICINFO.VALUE
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.TYPE
     *
     * @return the value of BASICINFO.TYPE
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.TYPE
     *
     * @param type the value for BASICINFO.TYPE
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.TAG
     *
     * @return the value of BASICINFO.TAG
     *
     * @mbggenerated
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.TAG
     *
     * @param tag the value for BASICINFO.TAG
     *
     * @mbggenerated
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.ISALIVE
     *
     * @return the value of BASICINFO.ISALIVE
     *
     * @mbggenerated
     */
    public String getIsalive() {
        return isalive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.ISALIVE
     *
     * @param isalive the value for BASICINFO.ISALIVE
     *
     * @mbggenerated
     */
    public void setIsalive(String isalive) {
        this.isalive = isalive == null ? null : isalive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.VCHAR1
     *
     * @return the value of BASICINFO.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.VCHAR1
     *
     * @param vchar1 the value for BASICINFO.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.VCHAR3
     *
     * @return the value of BASICINFO.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.VCHAR3
     *
     * @param vchar3 the value for BASICINFO.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BASICINFO.VCHAR2
     *
     * @return the value of BASICINFO.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BASICINFO.VCHAR2
     *
     * @param vchar2 the value for BASICINFO.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }
}