package com.yycg.pojo;

import java.math.BigDecimal;

public class BssSysArea extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.AREAID
     *
     * @mbggenerated
     */
    private String areaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.AREANAME
     *
     * @mbggenerated
     */
    private String areaname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.AREALEVEL
     *
     * @mbggenerated
     */
    private BigDecimal arealevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.AREAFULLNAME
     *
     * @mbggenerated
     */
    private String areafullname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.PARENTID
     *
     * @mbggenerated
     */
    private String parentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.SHORTNAME
     *
     * @mbggenerated
     */
    private String shortname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.ISUNIT
     *
     * @mbggenerated
     */
    private String isunit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.LASTUPDATE
     *
     * @mbggenerated
     */
    private String lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.YZCODE
     *
     * @mbggenerated
     */
    private String yzcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR4
     *
     * @mbggenerated
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR5
     *
     * @mbggenerated
     */
    private String vchar5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BSS_SYS_AREA.VCHAR6
     *
     * @mbggenerated
     */
    private String vchar6;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    public BssSysArea(String areaid, String areaname, BigDecimal arealevel, String areafullname, String parentid, String shortname, String isunit, String lastupdate, String yzcode, String vchar1, String vchar2, String vchar3, String vchar4, String vchar5, String vchar6) {
        this.areaid = areaid;
        this.areaname = areaname;
        this.arealevel = arealevel;
        this.areafullname = areafullname;
        this.parentid = parentid;
        this.shortname = shortname;
        this.isunit = isunit;
        this.lastupdate = lastupdate;
        this.yzcode = yzcode;
        this.vchar1 = vchar1;
        this.vchar2 = vchar2;
        this.vchar3 = vchar3;
        this.vchar4 = vchar4;
        this.vchar5 = vchar5;
        this.vchar6 = vchar6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    public BssSysArea() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.AREAID
     *
     * @return the value of BSS_SYS_AREA.AREAID
     *
     * @mbggenerated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.AREAID
     *
     * @param areaid the value for BSS_SYS_AREA.AREAID
     *
     * @mbggenerated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.AREANAME
     *
     * @return the value of BSS_SYS_AREA.AREANAME
     *
     * @mbggenerated
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.AREANAME
     *
     * @param areaname the value for BSS_SYS_AREA.AREANAME
     *
     * @mbggenerated
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname == null ? null : areaname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.AREALEVEL
     *
     * @return the value of BSS_SYS_AREA.AREALEVEL
     *
     * @mbggenerated
     */
    public BigDecimal getArealevel() {
        return arealevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.AREALEVEL
     *
     * @param arealevel the value for BSS_SYS_AREA.AREALEVEL
     *
     * @mbggenerated
     */
    public void setArealevel(BigDecimal arealevel) {
        this.arealevel = arealevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.AREAFULLNAME
     *
     * @return the value of BSS_SYS_AREA.AREAFULLNAME
     *
     * @mbggenerated
     */
    public String getAreafullname() {
        return areafullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.AREAFULLNAME
     *
     * @param areafullname the value for BSS_SYS_AREA.AREAFULLNAME
     *
     * @mbggenerated
     */
    public void setAreafullname(String areafullname) {
        this.areafullname = areafullname == null ? null : areafullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.PARENTID
     *
     * @return the value of BSS_SYS_AREA.PARENTID
     *
     * @mbggenerated
     */
    public String getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.PARENTID
     *
     * @param parentid the value for BSS_SYS_AREA.PARENTID
     *
     * @mbggenerated
     */
    public void setParentid(String parentid) {
        this.parentid = parentid == null ? null : parentid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.SHORTNAME
     *
     * @return the value of BSS_SYS_AREA.SHORTNAME
     *
     * @mbggenerated
     */
    public String getShortname() {
        return shortname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.SHORTNAME
     *
     * @param shortname the value for BSS_SYS_AREA.SHORTNAME
     *
     * @mbggenerated
     */
    public void setShortname(String shortname) {
        this.shortname = shortname == null ? null : shortname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.ISUNIT
     *
     * @return the value of BSS_SYS_AREA.ISUNIT
     *
     * @mbggenerated
     */
    public String getIsunit() {
        return isunit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.ISUNIT
     *
     * @param isunit the value for BSS_SYS_AREA.ISUNIT
     *
     * @mbggenerated
     */
    public void setIsunit(String isunit) {
        this.isunit = isunit == null ? null : isunit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.LASTUPDATE
     *
     * @return the value of BSS_SYS_AREA.LASTUPDATE
     *
     * @mbggenerated
     */
    public String getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.LASTUPDATE
     *
     * @param lastupdate the value for BSS_SYS_AREA.LASTUPDATE
     *
     * @mbggenerated
     */
    public void setLastupdate(String lastupdate) {
        this.lastupdate = lastupdate == null ? null : lastupdate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.YZCODE
     *
     * @return the value of BSS_SYS_AREA.YZCODE
     *
     * @mbggenerated
     */
    public String getYzcode() {
        return yzcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.YZCODE
     *
     * @param yzcode the value for BSS_SYS_AREA.YZCODE
     *
     * @mbggenerated
     */
    public void setYzcode(String yzcode) {
        this.yzcode = yzcode == null ? null : yzcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR1
     *
     * @return the value of BSS_SYS_AREA.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR1
     *
     * @param vchar1 the value for BSS_SYS_AREA.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR2
     *
     * @return the value of BSS_SYS_AREA.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR2
     *
     * @param vchar2 the value for BSS_SYS_AREA.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR3
     *
     * @return the value of BSS_SYS_AREA.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR3
     *
     * @param vchar3 the value for BSS_SYS_AREA.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR4
     *
     * @return the value of BSS_SYS_AREA.VCHAR4
     *
     * @mbggenerated
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR4
     *
     * @param vchar4 the value for BSS_SYS_AREA.VCHAR4
     *
     * @mbggenerated
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4 == null ? null : vchar4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR5
     *
     * @return the value of BSS_SYS_AREA.VCHAR5
     *
     * @mbggenerated
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR5
     *
     * @param vchar5 the value for BSS_SYS_AREA.VCHAR5
     *
     * @mbggenerated
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5 == null ? null : vchar5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BSS_SYS_AREA.VCHAR6
     *
     * @return the value of BSS_SYS_AREA.VCHAR6
     *
     * @mbggenerated
     */
    public String getVchar6() {
        return vchar6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BSS_SYS_AREA.VCHAR6
     *
     * @param vchar6 the value for BSS_SYS_AREA.VCHAR6
     *
     * @mbggenerated
     */
    public void setVchar6(String vchar6) {
        this.vchar6 = vchar6 == null ? null : vchar6.trim();
    }
}