package com.yycg.pojo;

import java.math.BigDecimal;

public class Dictinfo extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.DICTCODE
     *
     * @mbggenerated
     */
    private String dictcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.TYPECODE
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.INFO
     *
     * @mbggenerated
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.UPDATETIME
     *
     * @mbggenerated
     */
    private String updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.DICTSORT
     *
     * @mbggenerated
     */
    private BigDecimal dictsort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.ISENABLE
     *
     * @mbggenerated
     */
    private String isenable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTINFO.VALUETYPE
     *
     * @mbggenerated
     */
    private String valuetype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    public Dictinfo(String id, String dictcode, String typecode, String info, String remark, String updatetime, BigDecimal dictsort, String isenable, String valuetype) {
        this.id = id;
        this.dictcode = dictcode;
        this.typecode = typecode;
        this.info = info;
        this.remark = remark;
        this.updatetime = updatetime;
        this.dictsort = dictsort;
        this.isenable = isenable;
        this.valuetype = valuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    public Dictinfo() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.ID
     *
     * @return the value of DICTINFO.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.ID
     *
     * @param id the value for DICTINFO.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.DICTCODE
     *
     * @return the value of DICTINFO.DICTCODE
     *
     * @mbggenerated
     */
    public String getDictcode() {
        return dictcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.DICTCODE
     *
     * @param dictcode the value for DICTINFO.DICTCODE
     *
     * @mbggenerated
     */
    public void setDictcode(String dictcode) {
        this.dictcode = dictcode == null ? null : dictcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.TYPECODE
     *
     * @return the value of DICTINFO.TYPECODE
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.TYPECODE
     *
     * @param typecode the value for DICTINFO.TYPECODE
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.INFO
     *
     * @return the value of DICTINFO.INFO
     *
     * @mbggenerated
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.INFO
     *
     * @param info the value for DICTINFO.INFO
     *
     * @mbggenerated
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.REMARK
     *
     * @return the value of DICTINFO.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.REMARK
     *
     * @param remark the value for DICTINFO.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.UPDATETIME
     *
     * @return the value of DICTINFO.UPDATETIME
     *
     * @mbggenerated
     */
    public String getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.UPDATETIME
     *
     * @param updatetime the value for DICTINFO.UPDATETIME
     *
     * @mbggenerated
     */
    public void setUpdatetime(String updatetime) {
        this.updatetime = updatetime == null ? null : updatetime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.DICTSORT
     *
     * @return the value of DICTINFO.DICTSORT
     *
     * @mbggenerated
     */
    public BigDecimal getDictsort() {
        return dictsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.DICTSORT
     *
     * @param dictsort the value for DICTINFO.DICTSORT
     *
     * @mbggenerated
     */
    public void setDictsort(BigDecimal dictsort) {
        this.dictsort = dictsort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.ISENABLE
     *
     * @return the value of DICTINFO.ISENABLE
     *
     * @mbggenerated
     */
    public String getIsenable() {
        return isenable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.ISENABLE
     *
     * @param isenable the value for DICTINFO.ISENABLE
     *
     * @mbggenerated
     */
    public void setIsenable(String isenable) {
        this.isenable = isenable == null ? null : isenable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTINFO.VALUETYPE
     *
     * @return the value of DICTINFO.VALUETYPE
     *
     * @mbggenerated
     */
    public String getValuetype() {
        return valuetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTINFO.VALUETYPE
     *
     * @param valuetype the value for DICTINFO.VALUETYPE
     *
     * @mbggenerated
     */
    public void setValuetype(String valuetype) {
        this.valuetype = valuetype == null ? null : valuetype.trim();
    }
}