package com.yycg.pojo;

import java.math.BigDecimal;

public class Dicttype extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTTYPE.TYPECODE
     *
     * @mbggenerated
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTTYPE.TYPENAME
     *
     * @mbggenerated
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTTYPE.REMARK
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTTYPE.TYPESORT
     *
     * @mbggenerated
     */
    private BigDecimal typesort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DICTTYPE.CODELENGTH
     *
     * @mbggenerated
     */
    private String codelength;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    public Dicttype(String typecode, String typename, String remark, BigDecimal typesort, String codelength) {
        this.typecode = typecode;
        this.typename = typename;
        this.remark = remark;
        this.typesort = typesort;
        this.codelength = codelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    public Dicttype() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTTYPE.TYPECODE
     *
     * @return the value of DICTTYPE.TYPECODE
     *
     * @mbggenerated
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTTYPE.TYPECODE
     *
     * @param typecode the value for DICTTYPE.TYPECODE
     *
     * @mbggenerated
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTTYPE.TYPENAME
     *
     * @return the value of DICTTYPE.TYPENAME
     *
     * @mbggenerated
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTTYPE.TYPENAME
     *
     * @param typename the value for DICTTYPE.TYPENAME
     *
     * @mbggenerated
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTTYPE.REMARK
     *
     * @return the value of DICTTYPE.REMARK
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTTYPE.REMARK
     *
     * @param remark the value for DICTTYPE.REMARK
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTTYPE.TYPESORT
     *
     * @return the value of DICTTYPE.TYPESORT
     *
     * @mbggenerated
     */
    public BigDecimal getTypesort() {
        return typesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTTYPE.TYPESORT
     *
     * @param typesort the value for DICTTYPE.TYPESORT
     *
     * @mbggenerated
     */
    public void setTypesort(BigDecimal typesort) {
        this.typesort = typesort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DICTTYPE.CODELENGTH
     *
     * @return the value of DICTTYPE.CODELENGTH
     *
     * @mbggenerated
     */
    public String getCodelength() {
        return codelength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DICTTYPE.CODELENGTH
     *
     * @param codelength the value for DICTTYPE.CODELENGTH
     *
     * @mbggenerated
     */
    public void setCodelength(String codelength) {
        this.codelength = codelength == null ? null : codelength.trim();
    }
}