package com.yycg.pojo;

public class Usergysarea extends UsergysareaKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYSAREA.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYSAREA.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYSAREA.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYSAREA
     *
     * @mbggenerated
     */
    public Usergysarea(String usergysid, String areaid, String vchar1, String vchar2, String vchar3) {
        super(usergysid, areaid);
        this.vchar1 = vchar1;
        this.vchar2 = vchar2;
        this.vchar3 = vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYSAREA
     *
     * @mbggenerated
     */
    public Usergysarea() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYSAREA.VCHAR1
     *
     * @return the value of USERGYSAREA.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYSAREA.VCHAR1
     *
     * @param vchar1 the value for USERGYSAREA.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYSAREA.VCHAR2
     *
     * @return the value of USERGYSAREA.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYSAREA.VCHAR2
     *
     * @param vchar2 the value for USERGYSAREA.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYSAREA.VCHAR3
     *
     * @return the value of USERGYSAREA.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYSAREA.VCHAR3
     *
     * @param vchar3 the value for USERGYSAREA.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }
}