package com.yycg.pojo;

public class Usergys extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.ID
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.MC
     *
     * @mbggenerated
     */
    private String mc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.LB
     *
     * @mbggenerated
     */
    private String lb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XKZ
     *
     * @mbggenerated
     */
    private String xkz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XKZYXQ
     *
     * @mbggenerated
     */
    private String xkzyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.LXR
     *
     * @mbggenerated
     */
    private String lxr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.DH
     *
     * @mbggenerated
     */
    private String dh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.JYFW
     *
     * @mbggenerated
     */
    private String jyfw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.ZCDZ
     *
     * @mbggenerated
     */
    private String zcdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.LXDZ
     *
     * @mbggenerated
     */
    private String lxdz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.YZBM
     *
     * @mbggenerated
     */
    private String yzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.ZZC
     *
     * @mbggenerated
     */
    private String zzc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.CZ
     *
     * @mbggenerated
     */
    private String cz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.FRMC
     *
     * @mbggenerated
     */
    private String frmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.FRSFZ
     *
     * @mbggenerated
     */
    private String frsfz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.ZCZJ
     *
     * @mbggenerated
     */
    private String zczj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XSE
     *
     * @mbggenerated
     */
    private String xse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.DZYX
     *
     * @mbggenerated
     */
    private String dzyx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.WZ
     *
     * @mbggenerated
     */
    private String wz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.DMZH
     *
     * @mbggenerated
     */
    private String dmzh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.DMZHYXQ
     *
     * @mbggenerated
     */
    private String dmzhyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.YYZZ
     *
     * @mbggenerated
     */
    private String yyzz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.YYZZYXQ
     *
     * @mbggenerated
     */
    private String yyzzyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XYZ
     *
     * @mbggenerated
     */
    private String xyz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XYZBM
     *
     * @mbggenerated
     */
    private String xyzbm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.XYZYXQ
     *
     * @mbggenerated
     */
    private String xyzyxq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.GDZC
     *
     * @mbggenerated
     */
    private String gdzc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.BZ
     *
     * @mbggenerated
     */
    private String bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.VCHAR1
     *
     * @mbggenerated
     */
    private String vchar1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.VCHAR2
     *
     * @mbggenerated
     */
    private String vchar2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.VCHAR3
     *
     * @mbggenerated
     */
    private String vchar3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.VCHAR4
     *
     * @mbggenerated
     */
    private String vchar4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.VCHAR5
     *
     * @mbggenerated
     */
    private String vchar5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYS.JJ
     *
     * @mbggenerated
     */
    private String jj;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYS
     *
     * @mbggenerated
     */
    public Usergys(String id, String mc, String lb, String xkz, String xkzyxq, String lxr, String dh, String jyfw, String zcdz, String lxdz, String yzbm, String zzc, String cz, String frmc, String frsfz, String zczj, String xse, String dzyx, String wz, String dmzh, String dmzhyxq, String yyzz, String yyzzyxq, String xyz, String xyzbm, String xyzyxq, String gdzc, String bz, String vchar1, String vchar2, String vchar3, String vchar4, String vchar5, String jj) {
        this.id = id;
        this.mc = mc;
        this.lb = lb;
        this.xkz = xkz;
        this.xkzyxq = xkzyxq;
        this.lxr = lxr;
        this.dh = dh;
        this.jyfw = jyfw;
        this.zcdz = zcdz;
        this.lxdz = lxdz;
        this.yzbm = yzbm;
        this.zzc = zzc;
        this.cz = cz;
        this.frmc = frmc;
        this.frsfz = frsfz;
        this.zczj = zczj;
        this.xse = xse;
        this.dzyx = dzyx;
        this.wz = wz;
        this.dmzh = dmzh;
        this.dmzhyxq = dmzhyxq;
        this.yyzz = yyzz;
        this.yyzzyxq = yyzzyxq;
        this.xyz = xyz;
        this.xyzbm = xyzbm;
        this.xyzyxq = xyzyxq;
        this.gdzc = gdzc;
        this.bz = bz;
        this.vchar1 = vchar1;
        this.vchar2 = vchar2;
        this.vchar3 = vchar3;
        this.vchar4 = vchar4;
        this.vchar5 = vchar5;
        this.jj = jj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYS
     *
     * @mbggenerated
     */
    public Usergys() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.ID
     *
     * @return the value of USERGYS.ID
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.ID
     *
     * @param id the value for USERGYS.ID
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.MC
     *
     * @return the value of USERGYS.MC
     *
     * @mbggenerated
     */
    public String getMc() {
        return mc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.MC
     *
     * @param mc the value for USERGYS.MC
     *
     * @mbggenerated
     */
    public void setMc(String mc) {
        this.mc = mc == null ? null : mc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.LB
     *
     * @return the value of USERGYS.LB
     *
     * @mbggenerated
     */
    public String getLb() {
        return lb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.LB
     *
     * @param lb the value for USERGYS.LB
     *
     * @mbggenerated
     */
    public void setLb(String lb) {
        this.lb = lb == null ? null : lb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XKZ
     *
     * @return the value of USERGYS.XKZ
     *
     * @mbggenerated
     */
    public String getXkz() {
        return xkz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XKZ
     *
     * @param xkz the value for USERGYS.XKZ
     *
     * @mbggenerated
     */
    public void setXkz(String xkz) {
        this.xkz = xkz == null ? null : xkz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XKZYXQ
     *
     * @return the value of USERGYS.XKZYXQ
     *
     * @mbggenerated
     */
    public String getXkzyxq() {
        return xkzyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XKZYXQ
     *
     * @param xkzyxq the value for USERGYS.XKZYXQ
     *
     * @mbggenerated
     */
    public void setXkzyxq(String xkzyxq) {
        this.xkzyxq = xkzyxq == null ? null : xkzyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.LXR
     *
     * @return the value of USERGYS.LXR
     *
     * @mbggenerated
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.LXR
     *
     * @param lxr the value for USERGYS.LXR
     *
     * @mbggenerated
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.DH
     *
     * @return the value of USERGYS.DH
     *
     * @mbggenerated
     */
    public String getDh() {
        return dh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.DH
     *
     * @param dh the value for USERGYS.DH
     *
     * @mbggenerated
     */
    public void setDh(String dh) {
        this.dh = dh == null ? null : dh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.JYFW
     *
     * @return the value of USERGYS.JYFW
     *
     * @mbggenerated
     */
    public String getJyfw() {
        return jyfw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.JYFW
     *
     * @param jyfw the value for USERGYS.JYFW
     *
     * @mbggenerated
     */
    public void setJyfw(String jyfw) {
        this.jyfw = jyfw == null ? null : jyfw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.ZCDZ
     *
     * @return the value of USERGYS.ZCDZ
     *
     * @mbggenerated
     */
    public String getZcdz() {
        return zcdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.ZCDZ
     *
     * @param zcdz the value for USERGYS.ZCDZ
     *
     * @mbggenerated
     */
    public void setZcdz(String zcdz) {
        this.zcdz = zcdz == null ? null : zcdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.LXDZ
     *
     * @return the value of USERGYS.LXDZ
     *
     * @mbggenerated
     */
    public String getLxdz() {
        return lxdz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.LXDZ
     *
     * @param lxdz the value for USERGYS.LXDZ
     *
     * @mbggenerated
     */
    public void setLxdz(String lxdz) {
        this.lxdz = lxdz == null ? null : lxdz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.YZBM
     *
     * @return the value of USERGYS.YZBM
     *
     * @mbggenerated
     */
    public String getYzbm() {
        return yzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.YZBM
     *
     * @param yzbm the value for USERGYS.YZBM
     *
     * @mbggenerated
     */
    public void setYzbm(String yzbm) {
        this.yzbm = yzbm == null ? null : yzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.ZZC
     *
     * @return the value of USERGYS.ZZC
     *
     * @mbggenerated
     */
    public String getZzc() {
        return zzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.ZZC
     *
     * @param zzc the value for USERGYS.ZZC
     *
     * @mbggenerated
     */
    public void setZzc(String zzc) {
        this.zzc = zzc == null ? null : zzc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.CZ
     *
     * @return the value of USERGYS.CZ
     *
     * @mbggenerated
     */
    public String getCz() {
        return cz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.CZ
     *
     * @param cz the value for USERGYS.CZ
     *
     * @mbggenerated
     */
    public void setCz(String cz) {
        this.cz = cz == null ? null : cz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.FRMC
     *
     * @return the value of USERGYS.FRMC
     *
     * @mbggenerated
     */
    public String getFrmc() {
        return frmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.FRMC
     *
     * @param frmc the value for USERGYS.FRMC
     *
     * @mbggenerated
     */
    public void setFrmc(String frmc) {
        this.frmc = frmc == null ? null : frmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.FRSFZ
     *
     * @return the value of USERGYS.FRSFZ
     *
     * @mbggenerated
     */
    public String getFrsfz() {
        return frsfz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.FRSFZ
     *
     * @param frsfz the value for USERGYS.FRSFZ
     *
     * @mbggenerated
     */
    public void setFrsfz(String frsfz) {
        this.frsfz = frsfz == null ? null : frsfz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.ZCZJ
     *
     * @return the value of USERGYS.ZCZJ
     *
     * @mbggenerated
     */
    public String getZczj() {
        return zczj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.ZCZJ
     *
     * @param zczj the value for USERGYS.ZCZJ
     *
     * @mbggenerated
     */
    public void setZczj(String zczj) {
        this.zczj = zczj == null ? null : zczj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XSE
     *
     * @return the value of USERGYS.XSE
     *
     * @mbggenerated
     */
    public String getXse() {
        return xse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XSE
     *
     * @param xse the value for USERGYS.XSE
     *
     * @mbggenerated
     */
    public void setXse(String xse) {
        this.xse = xse == null ? null : xse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.DZYX
     *
     * @return the value of USERGYS.DZYX
     *
     * @mbggenerated
     */
    public String getDzyx() {
        return dzyx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.DZYX
     *
     * @param dzyx the value for USERGYS.DZYX
     *
     * @mbggenerated
     */
    public void setDzyx(String dzyx) {
        this.dzyx = dzyx == null ? null : dzyx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.WZ
     *
     * @return the value of USERGYS.WZ
     *
     * @mbggenerated
     */
    public String getWz() {
        return wz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.WZ
     *
     * @param wz the value for USERGYS.WZ
     *
     * @mbggenerated
     */
    public void setWz(String wz) {
        this.wz = wz == null ? null : wz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.DMZH
     *
     * @return the value of USERGYS.DMZH
     *
     * @mbggenerated
     */
    public String getDmzh() {
        return dmzh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.DMZH
     *
     * @param dmzh the value for USERGYS.DMZH
     *
     * @mbggenerated
     */
    public void setDmzh(String dmzh) {
        this.dmzh = dmzh == null ? null : dmzh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.DMZHYXQ
     *
     * @return the value of USERGYS.DMZHYXQ
     *
     * @mbggenerated
     */
    public String getDmzhyxq() {
        return dmzhyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.DMZHYXQ
     *
     * @param dmzhyxq the value for USERGYS.DMZHYXQ
     *
     * @mbggenerated
     */
    public void setDmzhyxq(String dmzhyxq) {
        this.dmzhyxq = dmzhyxq == null ? null : dmzhyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.YYZZ
     *
     * @return the value of USERGYS.YYZZ
     *
     * @mbggenerated
     */
    public String getYyzz() {
        return yyzz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.YYZZ
     *
     * @param yyzz the value for USERGYS.YYZZ
     *
     * @mbggenerated
     */
    public void setYyzz(String yyzz) {
        this.yyzz = yyzz == null ? null : yyzz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.YYZZYXQ
     *
     * @return the value of USERGYS.YYZZYXQ
     *
     * @mbggenerated
     */
    public String getYyzzyxq() {
        return yyzzyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.YYZZYXQ
     *
     * @param yyzzyxq the value for USERGYS.YYZZYXQ
     *
     * @mbggenerated
     */
    public void setYyzzyxq(String yyzzyxq) {
        this.yyzzyxq = yyzzyxq == null ? null : yyzzyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XYZ
     *
     * @return the value of USERGYS.XYZ
     *
     * @mbggenerated
     */
    public String getXyz() {
        return xyz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XYZ
     *
     * @param xyz the value for USERGYS.XYZ
     *
     * @mbggenerated
     */
    public void setXyz(String xyz) {
        this.xyz = xyz == null ? null : xyz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XYZBM
     *
     * @return the value of USERGYS.XYZBM
     *
     * @mbggenerated
     */
    public String getXyzbm() {
        return xyzbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XYZBM
     *
     * @param xyzbm the value for USERGYS.XYZBM
     *
     * @mbggenerated
     */
    public void setXyzbm(String xyzbm) {
        this.xyzbm = xyzbm == null ? null : xyzbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.XYZYXQ
     *
     * @return the value of USERGYS.XYZYXQ
     *
     * @mbggenerated
     */
    public String getXyzyxq() {
        return xyzyxq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.XYZYXQ
     *
     * @param xyzyxq the value for USERGYS.XYZYXQ
     *
     * @mbggenerated
     */
    public void setXyzyxq(String xyzyxq) {
        this.xyzyxq = xyzyxq == null ? null : xyzyxq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.GDZC
     *
     * @return the value of USERGYS.GDZC
     *
     * @mbggenerated
     */
    public String getGdzc() {
        return gdzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.GDZC
     *
     * @param gdzc the value for USERGYS.GDZC
     *
     * @mbggenerated
     */
    public void setGdzc(String gdzc) {
        this.gdzc = gdzc == null ? null : gdzc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.BZ
     *
     * @return the value of USERGYS.BZ
     *
     * @mbggenerated
     */
    public String getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.BZ
     *
     * @param bz the value for USERGYS.BZ
     *
     * @mbggenerated
     */
    public void setBz(String bz) {
        this.bz = bz == null ? null : bz.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.VCHAR1
     *
     * @return the value of USERGYS.VCHAR1
     *
     * @mbggenerated
     */
    public String getVchar1() {
        return vchar1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.VCHAR1
     *
     * @param vchar1 the value for USERGYS.VCHAR1
     *
     * @mbggenerated
     */
    public void setVchar1(String vchar1) {
        this.vchar1 = vchar1 == null ? null : vchar1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.VCHAR2
     *
     * @return the value of USERGYS.VCHAR2
     *
     * @mbggenerated
     */
    public String getVchar2() {
        return vchar2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.VCHAR2
     *
     * @param vchar2 the value for USERGYS.VCHAR2
     *
     * @mbggenerated
     */
    public void setVchar2(String vchar2) {
        this.vchar2 = vchar2 == null ? null : vchar2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.VCHAR3
     *
     * @return the value of USERGYS.VCHAR3
     *
     * @mbggenerated
     */
    public String getVchar3() {
        return vchar3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.VCHAR3
     *
     * @param vchar3 the value for USERGYS.VCHAR3
     *
     * @mbggenerated
     */
    public void setVchar3(String vchar3) {
        this.vchar3 = vchar3 == null ? null : vchar3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.VCHAR4
     *
     * @return the value of USERGYS.VCHAR4
     *
     * @mbggenerated
     */
    public String getVchar4() {
        return vchar4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.VCHAR4
     *
     * @param vchar4 the value for USERGYS.VCHAR4
     *
     * @mbggenerated
     */
    public void setVchar4(String vchar4) {
        this.vchar4 = vchar4 == null ? null : vchar4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.VCHAR5
     *
     * @return the value of USERGYS.VCHAR5
     *
     * @mbggenerated
     */
    public String getVchar5() {
        return vchar5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.VCHAR5
     *
     * @param vchar5 the value for USERGYS.VCHAR5
     *
     * @mbggenerated
     */
    public void setVchar5(String vchar5) {
        this.vchar5 = vchar5 == null ? null : vchar5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYS.JJ
     *
     * @return the value of USERGYS.JJ
     *
     * @mbggenerated
     */
    public String getJj() {
        return jj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYS.JJ
     *
     * @param jj the value for USERGYS.JJ
     *
     * @mbggenerated
     */
    public void setJj(String jj) {
        this.jj = jj == null ? null : jj.trim();
    }
}