package com.yycg.pojo;

public class UsergysareaKey extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYSAREA.USERGYSID
     *
     * @mbggenerated
     */
    private String usergysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERGYSAREA.AREAID
     *
     * @mbggenerated
     */
    private String areaid;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYSAREA
     *
     * @mbggenerated
     */
    public UsergysareaKey(String usergysid, String areaid) {
        this.usergysid = usergysid;
        this.areaid = areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERGYSAREA
     *
     * @mbggenerated
     */
    public UsergysareaKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYSAREA.USERGYSID
     *
     * @return the value of USERGYSAREA.USERGYSID
     *
     * @mbggenerated
     */
    public String getUsergysid() {
        return usergysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYSAREA.USERGYSID
     *
     * @param usergysid the value for USERGYSAREA.USERGYSID
     *
     * @mbggenerated
     */
    public void setUsergysid(String usergysid) {
        this.usergysid = usergysid == null ? null : usergysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERGYSAREA.AREAID
     *
     * @return the value of USERGYSAREA.AREAID
     *
     * @mbggenerated
     */
    public String getAreaid() {
        return areaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERGYSAREA.AREAID
     *
     * @param areaid the value for USERGYSAREA.AREAID
     *
     * @mbggenerated
     */
    public void setAreaid(String areaid) {
        this.areaid = areaid == null ? null : areaid.trim();
    }
}