package com.yycg.dao;

import com.yycg.pojo.BssSysArea;
import com.yycg.pojo.BssSysAreaExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BssSysAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int countByExample(BssSysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int deleteByExample(BssSysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int insert(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int insertSelective(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    List<BssSysArea> selectByExample(BssSysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    BssSysArea selectByPrimaryKey(String areaid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") BssSysArea record, @Param("example") BssSysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") BssSysArea record, @Param("example") BssSysAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(BssSysArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BSS_SYS_AREA
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(BssSysArea record);
}