package com.yycg.dao;

import com.yycg.pojo.Dicttype;
import com.yycg.pojo.DicttypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DicttypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int countByExample(DicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int deleteByExample(DicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String typecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int insert(Dicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int insertSelective(Dicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    List<Dicttype> selectByExample(DicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    Dicttype selectByPrimaryKey(String typecode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Dicttype record, @Param("example") DicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Dicttype record, @Param("example") DicttypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dicttype record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTTYPE
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dicttype record);
}