package com.yycg.dao;

import com.yycg.pojo.Dictinfo;
import com.yycg.pojo.DictinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DictinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int countByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int deleteByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int insert(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int insertSelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    List<Dictinfo> selectByExample(DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    Dictinfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Dictinfo record, @Param("example") DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Dictinfo record, @Param("example") DictinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Dictinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DICTINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Dictinfo record);
}