package com.yycg.dao;

import com.yycg.pojo.Useryy;
import com.yycg.pojo.UseryyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UseryyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int countByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int deleteByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int insert(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int insertSelective(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    List<Useryy> selectByExample(UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    Useryy selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Useryy record, @Param("example") UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Useryy record, @Param("example") UseryyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Useryy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERYY
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Useryy record);
}